filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /Users/sammiebae/Desktop/data-infra-notes/filebeats/*.log

output.console:
  pretty: true

output.kafka:
  hosts: ["localhost:9092"]
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000